#platform.team@lge.com	2011.01

obj-$(CONFIG_LGE_SENSOR_IMX105)+= sensor_imx105.o sensor_imx105_reg.o
obj-$(CONFIG_LGE_SENSOR_MT9P017)+= sensor_mt9p017.o sensor_mt9p017_reg.o
obj-$(CONFIG_LGE_SENSOR_MT9V113)+= sensor_mt9v113.o sensor_mt9v113_reg.o
obj-$(CONFIG_LGE_SENSOR_ISX005)+= sensor_isx005.o sensor_isx005_reg.o sensor_isx005_tun.o
obj-$(CONFIG_LGE_SENSOR_ISX006)+= sensor_isx006.o sensor_isx006_reg.o sensor_isx006_tun.o
obj-$(CONFIG_LGE_SENSOR_MT9M113)+= sensor_mt9m113.o sensor_mt9m113_reg.o
obj-$(CONFIG_LGE_SENSOR_MT9M114)+= sensor_mt9m114.o sensor_mt9m114_reg.o
obj-$(CONFIG_LGE_FLASH_AAT1270)+= flash_aat1270.o
obj-$(CONFIG_LGE_FLASH_LM3559)+= flash_lm3559.o lge_flash.o
obj-$(CONFIG_VTCAM_SD_IMAGE_TUNNING_FOR_MT9V113) += register_common_init.o
obj-$(CONFIG_LGE_PM_BH6172)+= pm_bh6172.o
