#platform.team@lge.com	2011.01

EXTRA_CFLAGS += -Iarch/arm/mach-msm
EXTRA_CFLAGS += -Iarch/arm/mach-msm/qdsp6v2
EXTRA_CFLAGS += -Ilge/include

obj-$(CONFIG_MACH_LGE_I_BOARD_LGU)	+= board_i_lgu.o
#obj-$(CONFIG_MACH_LGE_I_BOARD_LGU)	+= platform_i_lgu_bt.o
#obj-$(CONFIG_MACH_LGE_I_BOARD_LGU)	+= platform_i_lgu_camera.o
#obj-$(CONFIG_MACH_LGE_I_BOARD_LGU)	+= platform_i_lgu_input.o
#obj-$(CONFIG_MACH_LGE_I_BOARD_LGU)	+= platform_i_lgu_misc.o
#obj-$(CONFIG_MACH_LGE_I_BOARD_LGU)	+= platform_i_lgu_mmc.o
obj-$(CONFIG_MACH_LGE_I_BOARD_LGU)	+= platform_i_lgu_panel.o
obj-$(CONFIG_MACH_LGE_I_BOARD_LGU)	+= platform_i_lgu_snd.o
obj-$(CONFIG_MACH_LGE_I_BOARD_LGU)	+= gpiomux_i_lgu.o
obj-$(CONFIG_MACH_LGE_I_BOARD_LGU)	+= devices_i_lgu.o
