#platform.team@lge.com	2011.01
#
# Makefile for the sensor drivers.
#

# Each configuration option enables a list of files.

EXTRA_CFLAGS += -Ilge/include

obj-$(CONFIG_ATCMD_VIRTUAL_KBD) += atcmd_virtual_kbd.o
