#platform.team@lge.com	2011.01

EXTRA_CFLAGS += -Iarch/arm/mach-msm
EXTRA_CFLAGS += -Ilge/include

obj-$(CONFIG_MACH_LGE_I_BOARD)	+= devices_lge.o
obj-$(CONFIG_MACH_LGE_HDK_8x60)		+= hdk_8x60/
obj-$(CONFIG_MACH_LGE_I_BOARD_VZW)	+= i_vzw/
obj-$(CONFIG_MACH_LGE_I_BOARD_LGU)	+= i_lgu/
obj-$(CONFIG_MACH_LGE_C1_BOARD_MPS)	+= c1_mps/
