#
# Makefile for the Misc drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_ANDROID_VIBRATOR)	+= android_vibrator.o
obj-$(CONFIG_LGE_MUIC_TS5USBA33402)+= muic.o
obj-$(CONFIG_LGE_VIBRATOR)+= board-lge-vibrator.o
obj-$(CONFIG_LGE_HALLIC_CARKIT) += lge_hallic_carkit.o
obj-$(CONFIG_LGE_HALLIC_CARKIT) += lge_hallic_carkit.o
obj-$(CONFIG_LGE_FOTA_MISC_INFO) += lge_fota_sysfs.o
