#platform.team@lge.com	2011.01

EXTRA_CFLAGS += -Iarch/arm/mach-msm
EXTRA_CFLAGS += -Iarch/arm/mach-msm/qdsp6v2
EXTRA_CFLAGS += -Ilge/include

obj-$(CONFIG_MACH_LGE_HDK_8x60)	+= board_i_hdk.o
#obj-$(CONFIG_MACH_LGE_HDK_8x60)+= platform_i_hdk_bt.o
#obj-$(CONFIG_MACH_LGE_HDK_8x60)+= platform_i_hdk_camera.o
#obj-$(CONFIG_MACH_LGE_HDK_8x60)+= platform_i_hdk_input.o
#obj-$(CONFIG_MACH_LGE_HDK_8x60)+= platform_i_hdk_misc.o
#obj-$(CONFIG_MACH_LGE_HDK_8x60)+= platform_i_hdk_mmc.o
#obj-$(CONFIG_MACH_LGE_HDK_8x60)+= platform_i_hdk_panel.o
obj-$(CONFIG_MACH_LGE_HDK_8x60)+= platform_i_hdk_snd.o
obj-$(CONFIG_MACH_LGE_HDK_8x60)	+= gpiomux_i_hdk.o
obj-$(CONFIG_MACH_LGE_HDK_8x60)	+= devices_i_hdk.o
