#platform.team@lge.com	2011.01

EXTRA_CFLAGS += -Iarch/arm/mach-msm
EXTRA_CFLAGS += -Iarch/arm/mach-msm/qdsp6v2
EXTRA_CFLAGS += -Ilge/include

obj-$(CONFIG_MACH_LGE_C1_BOARD_MPS)+= board_c1_mps.o
obj-$(CONFIG_MACH_LGE_C1_BOARD_MPS)+= platform_c1_mps_bt.o
#obj-$(CONFIG_MACH_LGE_C1_BOARD_MPS)+= platform_c1_mps_camera.o
#obj-$(CONFIG_MACH_LGE_C1_BOARD_MPS)+= platform_c1_mps_input.o
#obj-$(CONFIG_MACH_LGE_C1_BOARD_MPS)+= platform_c1_mps_misc.o
#obj-$(CONFIG_MACH_LGE_C1_BOARD_MPS)+= platform_c1_mps_mmc.o
obj-$(CONFIG_MACH_LGE_C1_BOARD_MPS)+= platform_c1_mps_panel.o
obj-$(CONFIG_MACH_LGE_C1_BOARD_MPS)+= platform_c1_mps_snd.o
obj-$(CONFIG_MACH_LGE_C1_BOARD_MPS)+= gpiomux_c1_mps.o
obj-$(CONFIG_MACH_LGE_C1_BOARD_MPS)+= devices_c1_mps.o
