#platform.team@lge.com	2011.01

EXTRA_CFLAGS += -Iarch/arm/mach-msm
EXTRA_CFLAGS += -Iarch/arm/mach-msm/qdsp6v2
EXTRA_CFLAGS += -Ilge/include

obj-$(CONFIG_MACH_LGE_I_BOARD_VZW)	+= board_i_vzw.o

#[LG_BTUI] To seperate bt power driver module form All in One board configuration  minwoo2.kim@lge.com
obj-$(CONFIG_MACH_LGE_I_BOARD_VZW)	+= platform_i_vzw_bt.o

#obj-$(CONFIG_MACH_LGE_I_BOARD_VZW)	+= platform_i_vzw_camera.o
#obj-$(CONFIG_MACH_LGE_I_BOARD_VZW)	+= platform_i_vzw_input.o
#obj-$(CONFIG_MACH_LGE_I_BOARD_VZW)	+= platform_i_vzw_misc.o
#obj-$(CONFIG_MACH_LGE_I_BOARD_VZW)	+= platform_i_vzw_mmc.o
obj-$(CONFIG_MACH_LGE_I_BOARD_VZW)	+= platform_i_vzw_panel.o
obj-$(CONFIG_MACH_LGE_I_BOARD_VZW)	+= platform_i_vzw_snd.o
obj-$(CONFIG_MACH_LGE_I_BOARD_VZW)	+= gpiomux_i_vzw.o
obj-$(CONFIG_MACH_LGE_I_BOARD_VZW)	+= devices_i_vzw.o
